//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1714jlindahl2H
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int Id { get; set; }
        public string DateBorrowed { get; set; }
        public string DateReturned { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Person Lender { get; set; }
        public virtual Person Borrower { get; set; }
    }
}
